spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/opstrack}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

server.port=${PORT:8081}
