spring.application.name=backend

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/opstrack
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Web server
server.port=8081